### ISSUE TITLE
BlockChain Collaboration

### ISSUE THREAD

**Issue by kingsleyh** [bradford-hamilton/crystal-blockchain#1]
Hi 

Great work on your blockchain. We were wondering if you would be interested in contributing to our blockchain project here:  https://github.com/SushiChain/SushiChain - since you also have an interest in blockchain :)

our website:  https://sushichain.io

**Comment by bradford-hamilton** [comment]
Thanks. Really happy to see you have a badass blockchain project in Crystal! Will keep my eye on it 😃
